### ISSUE TITLE
Questions around your solution

### ISSUE THREAD

**Issue by otaviosoares** [Morriz/k8sdemo-api#1]
I got here from your [post](https://github.com/wercker/workflows-kubernetes-demo/issues/2).

I have some questions around your solution.

1 - I understand that $KUBE_CONFIG_PROD is a wercker env variable. Is it mandatory? What should be put there? [source code](https://github.com/Morriz/k8sdemo-api/blob/master/wercker.yml#L57-L59)
2 - Do you previously create the initial Deployment or does morriz/kube-deploy do it for the first time?

Thank you

**Comment by Morriz** [comment]
Sorry for the late reply, but I was kinda offline...but to get back:

$KUBE_CONFIG_PROD should contain the contents of the kubeconfig file that holds all the details to talk to your remote cluster. It should have base64-encoded strings for the following fields:
- certificate-authority-data
- client-certificate-data
- client-key-data

And yes, the deployment should exist. The updater looks for the deployment's containername:version and updates the version to the one given ($WERCKER_GIT_COMMIT)

Hope this helps :)

**Comment by otaviosoares** [comment]
Thank you @Morriz 

Everything worked now.
